### ISSUE TITLE
Praca domowa 2

### ISSUE THREAD

**Issue by dzienisz** [kbrzek/daftacademy_frontend4begginers#3]
https://github.com/kbrzek/daftacademy_frontend4begginers/blob/17d9b5915a7e7ec49a4a3e1113b7d7f0c07233aa/SzkieletStronyv2.html#L10

![zrzut ekranu 2018-11-20 o 16 40 42](https://user-images.githubusercontent.com/3521624/48784934-f19b0580-ece3-11e8-9371-869c61ad6a10.png)
![zrzut ekranu 2018-11-20 o 16 46 36](https://user-images.githubusercontent.com/3521624/48784933-f19b0580-ece3-11e8-908c-67993553fefc.png)

Zainstaluj sobie proszę Visual Studio Code. Znalazłem u Ciebie mały błąd, który łatwo wykryć w takim programie.

**Comment by kbrzek** [comment]
Dziękuję. Używam VSD tylko miałam ustawione takie kolory, że zaznaczenie błędu nie było czytelne. Po zmianie na "dark" jest ok.
